/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Lato', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        subl: {
          blue: {
            50: "hsl(var(--subl-blue-50))",
            100: "hsl(var(--subl-blue-100))",
            200: "hsl(var(--subl-blue-200))",
            300: "hsl(var(--subl-blue-300))",
            400: "hsl(var(--subl-blue-400))",
            500: "hsl(var(--subl-blue-500))",
            600: "hsl(var(--subl-blue-600))",
            700: "hsl(var(--subl-blue-700))",
            800: "hsl(var(--subl-blue-800))",
            900: "hsl(var(--subl-blue-900))",
          },
          grey: {
            50: "hsl(var(--subl-grey-50))",
            100: "hsl(var(--subl-grey-100))",
            200: "hsl(var(--subl-grey-200))",
            300: "hsl(var(--subl-grey-300))",
            400: "hsl(var(--subl-grey-400))",
            500: "hsl(var(--subl-grey-500))",
            600: "hsl(var(--subl-grey-600))",
            700: "hsl(var(--subl-grey-700))",
            800: "hsl(var(--subl-grey-800))",
            900: "hsl(var(--subl-grey-900))",
          },
          green: {
            50: "hsl(var(--subl-green-50))",
            100: "hsl(var(--subl-green-100))",
            200: "hsl(var(--subl-green-200))",
            300: "hsl(var(--subl-green-300))",
            400: "hsl(var(--subl-green-400))",
            500: "hsl(var(--subl-green-500))",
            600: "hsl(var(--subl-green-600))",
            700: "hsl(var(--subl-green-700))",
            800: "hsl(var(--subl-green-800))",
            900: "hsl(var(--subl-green-900))",
          },
          orange: {
            50: "hsl(var(--subl-orange-50))",
            100: "hsl(var(--subl-orange-100))",
            200: "hsl(var(--subl-orange-200))",
            300: "hsl(var(--subl-orange-300))",
            400: "hsl(var(--subl-orange-400))",
            500: "hsl(var(--subl-orange-500))",
            600: "hsl(var(--subl-orange-600))",
            700: "hsl(var(--subl-orange-700))",
            800: "hsl(var(--subl-orange-800))",
            900: "hsl(var(--subl-orange-900))",
          },
          red: {
            50: "hsl(var(--subl-red-50))",
            100: "hsl(var(--subl-red-100))",
            200: "hsl(var(--subl-red-200))",
            300: "hsl(var(--subl-red-300))",
            400: "hsl(var(--subl-red-400))",
            500: "hsl(var(--subl-red-500))",
            600: "hsl(var(--subl-red-600))",
            700: "hsl(var(--subl-red-700))",
            800: "hsl(var(--subl-red-800))",
            900: "hsl(var(--subl-red-900))",
          },
        },
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}